
package arabakiralamaotomasyonu;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author EKREM
 */
public class ArabaKirala extends javax.swing.JFrame {

    Crud crud1=new Crud();
    Crud crud2=new Crud();
    int arabaId;
    public ArabaKirala() {
        initComponents();
        plakaYaz();
        isimYaz();
        crud1.arabaTable(tblAraba);
        crud2.musteriTable(tblMusteri);
        
    }

    
    public void plakaYaz(){
        tblAraba.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                String durum=((String)crud1.model.getValueAt(tblAraba.getSelectedRow(),4));
                if(durum.equals("Kiralanamaz")){
                    JOptionPane.showMessageDialog(null, "Bu araç şu anda kiralanamaz.Lütfen listeden başka bir araç seçin.");
                }else{
                    arabaId=(Integer)crud1.model.getValueAt(tblAraba.getSelectedRow(),0);
                    txtPlaka.setText((String)crud1.model.getValueAt(tblAraba.getSelectedRow(),1));
                }
                
                
                
            }
        });
    }
    public void isimYaz(){
        tblMusteri.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                txtIsim.setText((String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),1)+" "+(String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),2));
                
                
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAraba = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnMusteri = new javax.swing.JButton();
        btnAraba = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMusteri = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlaka = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIsim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtGun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTemizle = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tarFatura = new javax.swing.JTextArea();
        btnHesapla = new javax.swing.JButton();
        btnFatura = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblHesap = new javax.swing.JLabel();
        btnKirala = new javax.swing.JButton();
        btnYazdir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tblAraba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "arabaId", "PLAKA", "MARKA", "MODEL", "DURUM", "GÜNLÜK ÜCRET(TL)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAraba);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        btnMusteri.setBackground(new java.awt.Color(0, 204, 102));
        btnMusteri.setText("Müşteri İşlemleri");
        btnMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusteriActionPerformed(evt);
            }
        });

        btnAraba.setBackground(new java.awt.Color(0, 204, 102));
        btnAraba.setText("Araba  İşlemleri");
        btnAraba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArabaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMusteri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAraba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAraba, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblMusteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "müsteriId", "Ad", "Soyad", "Adres", "Telefon", "Eposta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMusteri);

        jLabel1.setText("Araba Plaka");

        jLabel2.setText("Müşteri Ad Soyad");

        jLabel3.setText("Kiralama Tarihi");

        jLabel4.setText("Kiralama Süresi(Gün)");

        btnTemizle.setText("Satırları Temizle");
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPlaka)
                    .addComponent(txtIsim)
                    .addComponent(txtDate)
                    .addComponent(txtGun, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPlaka, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIsim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kiralama", jPanel2);

        tarFatura.setColumns(20);
        tarFatura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tarFatura.setRows(5);
        tarFatura.setText("             Fatura");
        jScrollPane4.setViewportView(tarFatura);

        jTabbedPane1.addTab("Fatura", jScrollPane4);

        btnHesapla.setText("Fiyat Hesapla");
        btnHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesaplaActionPerformed(evt);
            }
        });

        btnFatura.setText("Fatura Oluştur");
        btnFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));

        lblHesap.setBackground(new java.awt.Color(255, 255, 255));
        lblHesap.setText("0 TL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnKirala.setText("Arabayı Kirala");
        btnKirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiralaActionPerformed(evt);
            }
        });

        btnYazdir.setBackground(new java.awt.Color(0, 153, 255));
        btnYazdir.setText("Faturayı Yazdır");
        btnYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYazdirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnHesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnKirala, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnYazdir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnYazdir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHesapla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKirala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusteriActionPerformed
        MusteriList musteriList=new MusteriList();
        musteriList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMusteriActionPerformed

    private void btnArabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArabaActionPerformed
       ArabaList arabaList=new ArabaList();
       arabaList.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnArabaActionPerformed
int check=0;
int kirala=0;
    private void btnHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesaplaActionPerformed
        if(tblMusteri.getSelectedRowCount()==1 && tblAraba.getSelectedRowCount()==1 && !(txtGun.getText().equals("")) && !(txtDate.getText().equals(""))){
            int hesap=crud1.hesapla(Integer.valueOf(crud1.model.getValueAt(tblAraba.getSelectedRow(),5).toString()),Integer.valueOf(txtGun.getText()));
            lblHesap.setText(hesap+" TL");
            JOptionPane.showMessageDialog(null, "Fiyat Hesaplama Başarılı.Faturanızı oluşturabilirsiniz.");
            check=1;
        }else{
            JOptionPane.showMessageDialog(null,"Lütfen Bilgileri Eksiksiz Giriniz");
        }
            
    }//GEN-LAST:event_btnHesaplaActionPerformed

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
        txtPlaka.setText("");
        txtIsim.setText("");
        txtDate.setText("");
        txtGun.setText("");
        lblHesap.setText("0 TL");
        tarFatura.setText("\tFatura");
        check=0;
        kirala=0;

    }//GEN-LAST:event_btnTemizleActionPerformed

    private void btnFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaActionPerformed
        if(check==1){
            tarFatura.setText("\t\t\t\t\t\t\t\tFATURA          \nAraç Bilgileri\nPlaka: "+(String)crud1.model.getValueAt(tblAraba.getSelectedRow(),1)+"\nMarka: "+(String)crud1.model.getValueAt(tblAraba.getSelectedRow(),2)+
                    "\nModel: "+(String)crud1.model.getValueAt(tblAraba.getSelectedRow(),3)+"\nKiralama Ücreti: "+lblHesap.getText()+"\n\nMüşteri Bilgileri\nAd Soyad: "
            +(String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),1)+" "+(String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),2)+"\nAdres: "+(String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),3)+"\nTelefon: "+(String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),4)+
                    "\nEposta: "+(String)crud2.model.getValueAt(tblMusteri.getSelectedRow(),5)+"\nAraç Kiralama Tarihi: "+txtDate.getText()+"\nAraç Kiralama Süresi(Gün): "+txtGun.getText()+"\n\n\tLüTFEN ARACINIZI TESLİM GÜNÜ İÇERİSİNDE EN GEÇ SAAT 17:00'a KADAR TESLİM EDİNİZ.İYİ GÜNLER...");
            kirala=1;
            JOptionPane.showMessageDialog(null, "Faturanız Başarıyla Oluşturuldu");
        }if(check==0){
            JOptionPane.showMessageDialog(null, "Lütfen Önce Fiyatı Hesaplayınız");
        }
    }//GEN-LAST:event_btnFaturaActionPerformed

    private void btnKiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiralaActionPerformed
        if(kirala==1){
            Connection connection=null;
        DbHelper helper=new DbHelper();
        PreparedStatement statement=null;
        
        
        if(tblAraba.getSelectedRowCount()==1){
            
            
        try{
            connection=helper.getConnection();
            String sql="update arabalar set durum='Kiralanamaz' where arabaID="+arabaId+"";
            statement=connection.prepareStatement(sql);
            int result=statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Arabanız Kiralandı.İyi Günler...");
            crud1.arabaTable(tblAraba);
        }catch(SQLException exception){
            helper.showErrorMessage(exception);
        }finally{
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
                
            }
        }
        }
        }
    }//GEN-LAST:event_btnKiralaActionPerformed

    private void btnYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYazdirActionPerformed
        JFileChooser fileChooser=new JFileChooser();
        BufferedWriter writer=null;
         if(kirala==1){      
        try{
            int response=fileChooser.showOpenDialog(null);
            if(response==0){
            File file=new File(fileChooser.getSelectedFile().getAbsolutePath());
            writer=new BufferedWriter(new FileWriter(file,false));
            
            writer.write(tarFatura.getText());
            JOptionPane.showMessageDialog(null, "Faturanızı dosyadan yazdırabilirsiniz.");
            }
        }catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
         }if(kirala==0){
             JOptionPane.showMessageDialog(null, "Lütfen Faturanızı oluşturunuz.");
         }
        
        
        
    }//GEN-LAST:event_btnYazdirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArabaKirala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArabaKirala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArabaKirala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArabaKirala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArabaKirala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAraba;
    private javax.swing.JButton btnFatura;
    private javax.swing.JButton btnHesapla;
    private javax.swing.JButton btnKirala;
    private javax.swing.JButton btnMusteri;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JButton btnYazdir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHesap;
    private javax.swing.JTextArea tarFatura;
    private javax.swing.JTable tblAraba;
    private javax.swing.JTable tblMusteri;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtGun;
    private javax.swing.JTextField txtIsim;
    private javax.swing.JTextField txtPlaka;
    // End of variables declaration//GEN-END:variables
}
