
package arabakiralamaotomasyonu;

import static arabakiralamaotomasyonu.SplashEkrani.jProgressBar1;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author EKREM
 */
public class Giris extends javax.swing.JFrame {

    
    public Giris() {
        
        initComponents();
        
        
    }
    
    public static void yuklemeEkrani(){
    
        SplashEkrani splashEkrani=new SplashEkrani();
        splashEkrani.setVisible(true);
        
        try{
            for (int i=0;i<=100;i=i+10){
                Thread.sleep(200);
                jProgressBar1.setValue(i);
                jProgressBar1.setString("%"+i+" Loading...");
                
                if(i==100){
                    splashEkrani.setVisible(false);
                    
                }
            }
        }catch(InterruptedException e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnYeni = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblUnut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 160, -1));

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblName.setText("Kullanıcı Adı :");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 120, 22));

        lblPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblPassword.setText("Şifre :");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, 22));

        btnGiris.setText("Giriş Yap");
        btnGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });
        jPanel1.add(btnGiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 90, 40));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 160, -1));

        btnYeni.setText("Kaydol");
        btnYeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniActionPerformed(evt);
            }
        });
        jPanel1.add(btnYeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 90, 40));

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 90, 70));

        lblUnut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnut.setForeground(new java.awt.Color(0, 0, 255));
        lblUnut.setText("Şifremi Unuttum");
        lblUnut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUnutMouseClicked(evt);
            }
        });
        jPanel1.add(lblUnut, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arabakiralamaotomasyonu/Giris.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnYeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniActionPerformed
        Kaydol kaydol = new Kaydol();
        kaydol.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnYeniActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed

        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        if(!(txtName.getText().equals("")||txtPassword.getText().equals(""))){
        try {
            String nickname=txtName.getText();
            String sifre=txtPassword.getText();
            connection = helper.getConnection();
            statement=connection.createStatement();
            resultSet=statement.executeQuery("select count(idkullanici) as giris from kullanici where nickname='"+nickname+"'and sifre='"+sifre+"'");

            while(resultSet.next()){
                resultSet.getInt("giris");
                if(resultSet.getInt("giris")==0){
                    JOptionPane.showMessageDialog(null, "Hatalı Kullanıcı Adı Veya Şifre");
                } if(resultSet.getInt("giris")==1) {
                    ArabaList arabaList=new ArabaList();
                    arabaList.setVisible(true);
                    this.setVisible(false);
                }
            }

        } catch (SQLException exception) {
            helper.showErrorMessage(exception);
        } finally{
            try {
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Lütfen Bilgilerinizi Eksiksiz Giriniz");
            
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    private void lblUnutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnutMouseClicked
        Password password=new Password();
        password.setVisible(true);
        
    }//GEN-LAST:event_lblUnutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        yuklemeEkrani();
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnYeni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUnut;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
